sudo: required

language: python

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix
python:
  - "3.6"

# test stage
services:
  - docker

install:
  - docker run -d --name streams -p 4222:4222 nats-streaming:0.6.0
  - pip install protobuf # HACK!
  - pip install -r requirements/common.txt
  - pip install -r requirements/ci.txt
  - isort -rc -c --diff -m 3 setup.py rampante examples tests
  - flake8 setup.py rampante examples tests
  - mypy setup.py rampante examples tests --ignore-missing-imports
  - py.test --cov rampante --cov tests

script:
  - tox
  - python setup.py check -rms

after_success:
  - codecov

after_script:
  - docker rm -f streams

# other stages

