sudo: required

language: python

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix
python:
  - "3.6"

# test stage
services:
  - docker

install:
  - docker run -d --name streams -p 4222:4222 nats-streaming:0.6.0
  - pip install -r requirements/ci.txt

script:
  - tox
  - python setup.py check -rms

after_success:
  - codecov

after_script:
  - docker rm -f streams

# other stages
