# Copyright (c) 2017, Cassiny.io OÜ

# Image for MissionControlCenter

FROM python:3.11.5

LABEL maintainer "wow@cassiny.io"

USER root

RUN mkdir /src
WORKDIR /src
COPY . /src

# Install python packages
RUN pip install tox

# Configure container startup
CMD ["tox"]
